/**
 * Deterministic URL normalization.
 *
 * Pure, no I/O, no "server-only" dependency -- same pattern as
 * relationshipCanonicalization.ts. This module has no opinion on SSRF
 * safety (see urlSafety.ts) and no opinion on network reachability; it
 * only answers "what is the deterministic normalized form of this URL
 * string", for two consumers:
 *
 *   - ingestion_jobs.normalized_url / source_items.normalized_url
 *     (identity/candidate-match representation, NOT globally unique --
 *     see migration 0007 and docs/architecture.md)
 *   - future duplicate-detection logic (same normalized URL + same
 *     raw_content_hash -> duplicate; same normalized URL + different
 *     hash -> needs_review)
 *
 * `submittedUrl` (whatever the admin/provider supplied) is never touched
 * by this module and must be stored separately, unmodified, for audit
 * history -- see the approved URL model in the Phase 4 PR 2 spec.
 *
 * These functions are also intended to be reusable later on a
 * publisher-declared `canonicalUrl` discovered during HTML parsing (a
 * distinct concept from `normalizedUrl` -- not implemented in this PR).
 */

/**
 * Deliberately a small, explicit list rather than a pattern match (e.g.
 * "strip anything starting with utm_") -- broadening this speculatively
 * risks stripping a legitimate application query parameter that happens
 * to share a prefix. Extend only when a new tracking parameter is
 * actually observed and approved, per the standing instruction not to
 * broaden this list speculatively.
 */
const TRACKING_PARAMETERS: ReadonlySet<string> = new Set(
  [
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "gclid",
    "fbclid",
    "mc_cid",
    "mc_eid",
    "igshid",
    "ref",
    "ref_src",
    "spm",
    "cmp",
  ].map((p) => p.toLowerCase())
);

/**
 * Matching is case-insensitive on the parameter *name* (not its value).
 * There is no RFC that mandates a particular case for query parameter
 * names, and in practice tracking parameters are generated by many
 * different tools/platforms that are inconsistent about casing (e.g.
 * "UTM_Source" appears in the wild alongside "utm_source"). Case-
 * sensitive matching would silently let those variants through, which
 * defeats the purpose of the strip list. This is deliberately narrower
 * than it sounds: it only affects the fixed TRACKING_PARAMETERS names
 * above, never arbitrary/unknown parameters, which keep their exact
 * name and are never case-folded.
 */
function isTrackingParameter(name: string): boolean {
  return TRACKING_PARAMETERS.has(name.toLowerCase());
}

const DEFAULT_PORT_BY_SCHEME: Readonly<Record<string, string>> = {
  "http:": "80",
  "https:": "443",
};

export type UrlNormalizationErrorCode =
  | "malformed"
  | "unsupported_scheme"
  | "credentials_present";

export interface UrlNormalizationError {
  code: UrlNormalizationErrorCode;
  /** Safe, generic message -- never echoes the raw input back. */
  message: string;
}

export type UrlNormalizationResult =
  | { ok: true; normalizedUrl: string }
  | { ok: false; error: UrlNormalizationError };

/**
 * Normalizes a syntactically valid absolute http(s) URL into a
 * deterministic string suitable for storing in `normalized_url`.
 *
 * This is NOT a safety check -- it does not resolve DNS, does not know
 * about private IP ranges, and normalizing a URL does not mean it is
 * safe to fetch. Callers that will actually issue a request must run
 * `validatePublicHttpUrl` (and `resolveAndValidatePublicHost` for
 * hostnames) from urlSafety.ts as well, separately.
 */
export function normalizeUrl(input: string): UrlNormalizationResult {
  let url: URL;
  try {
    url = new URL(input);
  } catch {
    return {
      ok: false,
      error: { code: "malformed", message: "Not a syntactically valid absolute URL." },
    };
  }

  if (url.protocol !== "http:" && url.protocol !== "https:") {
    return {
      ok: false,
      error: { code: "unsupported_scheme", message: "Only http and https URLs are supported." },
    };
  }

  // Rejected here (not silently dropped) -- credentials embedded in a
  // URL are almost always a mistake or an attempted injection, and
  // silently stripping them would change the caller's intended target
  // without telling them. urlSafety.ts independently re-checks this so
  // the two modules remain safe to use separately (e.g. urlSafety may
  // run on a canonicalUrl that never passed through this function).
  if (url.username !== "" || url.password !== "") {
    return {
      ok: false,
      error: { code: "credentials_present", message: "URLs with embedded credentials are not supported." },
    };
  }

  // Scheme/host are already lowercased by the URL parser itself.

  // Remove fragment -- never sent to a server, never part of resource
  // identity for our purposes.
  url.hash = "";

  // Remove default port. The WHATWG URL parser already omits the
  // default port for these two schemes when serializing (verified: constructing
  // `new URL("http://example.com:80/")` yields a `.port` of `""`), so
  // this is a defensive, explicit no-op in the common case rather than
  // something this function strictly needs -- kept explicit because the
  // requirement calls it out directly and because relying on an
  // implicit parser behavior for a persisted identity column is fragile
  // across engine versions.
  if (url.port === DEFAULT_PORT_BY_SCHEME[url.protocol]) {
    url.port = "";
  }

  // Trailing slash: root "/" is left alone; a non-root path with a
  // trailing slash has it removed ("/foo/" -> "/foo"). We deliberately
  // do NOT touch path casing or percent-encoding beyond what the URL
  // parser does on its own -- inventing normalization there risks
  // conflating two paths that a server actually treats differently.
  if (url.pathname !== "/" && url.pathname.endsWith("/")) {
    url.pathname = url.pathname.slice(0, -1);
  }

  // Query parameters: strip approved tracking parameters, keep every
  // other parameter (including unrecognized ones) with its original
  // value, preserve repeated keys as repeated entries, and sort the
  // retained entries deterministically.
  //
  // Sorting is a plain ordinal string comparison on the literal key --
  // NOT case-folded. Unlike tracking-parameter matching (which is
  // deliberately lenient because those names are noise), an
  // application-meaningful parameter like "Id" and "id" may be two
  // genuinely different parameters to whatever consumes this URL, so we
  // must not conflate them by sorting case-insensitively.
  //
  // Sort stability: Array.prototype.sort is stable per spec (ES2019+),
  // so entries that share the same key retain their original relative
  // order -- this is what makes duplicate-key preservation deterministic
  // rather than just "not collapsed".
  const retainedEntries = [...url.searchParams.entries()].filter(
    ([key]) => !isTrackingParameter(key)
  );
  retainedEntries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

  const rebuiltParams = new URLSearchParams();
  for (const [key, value] of retainedEntries) {
    rebuiltParams.append(key, value);
  }
  // -------------------------------------------------------------------
  // Design decision: accept WHATWG application/x-www-form-urlencoded
  // canonical serialization as part of the normalization contract.
  //
  // Rebuilding via URLSearchParams re-encodes every retained value using
  // that algorithm rather than preserving the original URL's exact
  // percent-encoding. This was evaluated deliberately (not just assumed
  // safe) against the specific correctness question that matters for a
  // deterministic identity column: could this ever make two
  // semantically DIFFERENT query values compare equal, or two
  // semantically IDENTICAL query values compare different? Checked
  // empirically against every case called out in review:
  //
  //   - "%20" and a literal "+" both decode to a space and both
  //     re-serialize to "+". They are being treated as equivalent --
  //     but that IS the correct outcome, not an accidental merge: "+"
  //     meaning space in a query string is the same
  //     application/x-www-form-urlencoded convention that
  //     URL#searchParams itself is built on, and that essentially every
  //     browser, Node's own fetch, and most HTTP tooling already use to
  //     interpret query strings. Treating them as different identities
  //     would be the inconsistent choice, not this one.
  //   - "%2B" (an explicitly encoded literal "+") decodes to a literal
  //     "+" character -- NOT a space -- and re-serializes back to
  //     "%2B", staying distinct from an unencoded "+"/"%20". Verified:
  //     a value containing a real plus sign is never confused with a
  //     value containing a space.
  //   - Percent-hex case ("%2f" vs "%2F") is normalized to a single
  //     consistent case on output. This isn't a risk, it's a benefit:
  //     it collapses two syntactically different encodings of the exact
  //     same decoded value into one identity, which is the entire point
  //     of a normalized identity column.
  //   - Percent-encoded reserved characters that are meaningful to URL
  //     syntax if left bare ("%3D" for "=", "%26" for "&") are
  //     re-encoded on output, never left literal -- so they can never
  //     be misread as an extra delimiter.
  //
  //   The one genuine, narrow edge case: a source that emits a bare,
  //   UNENCODED "+" in a query value actually intending a literal plus
  //   character (rather than a space) will have that intent
  //   reinterpreted as a space. RFC 3986 alone does not define what a
  //   bare "+" in a query means -- that meaning only comes from the
  //   forms convention this module (and the rest of the ecosystem)
  //   applies. A source that wants an unambiguous literal plus should
  //   encode it as "%2B", which round-trips correctly (see above). This
  //   is an inherent ambiguity of query-string interpretation in
  //   general, not something introduced by this function, and
  //   `submittedUrl` (stored separately, untouched) remains the
  //   audit-accurate original if that ambiguity ever needs to be
  //   revisited for a specific URL.
  //
  // Conclusion: kept as-is. This is a standards-based, deterministic
  // canonicalization that strengthens identity-matching (collapsing
  // encoding variants of the same value) without conflating genuinely
  // different decoded values, aside from the one narrow, industry-wide
  // "+" convention described above.
  // -------------------------------------------------------------------
  url.search = rebuiltParams.toString();

  return { ok: true, normalizedUrl: url.toString() };
}
